### PR TITLE
Adding project support for linting

### PR DESCRIPTION
**Pull request by jamesallenuk**
I noticed that the project has an eslint config but hasn't got the required devDependencies or an npm script for running the linter across all files from within the project itself.

Not sure if you want to add this in but I thought I'd set it up. All the correct dependencies have been added for airbnb and Babel. I've also added an npm script: `npm run lint` which will lint all files in ./client along with the Webpack config file.

Due to - I am assuming - the way Webpack resolves dependencies when bundling, there are a lot of 'import/no-unresolved' linting errors when this is run so it's probably worth disabling this rule?

### CODE REVIEW

**Comment by grgur** [comment]
Yes, that was my fault because I have a global eslint setup so I don't have to introduce it in every project. My bad for not including it here.

I'm ok with disabling`import/no-unresolved`

**Comment by jamesallenuk** [comment]
Ah that's exactly what I assumed to be honest.

I've just added the following exclusions to the rules:

 `import/no-extraneous-dependencies: 0
 import/no-unresolved: 0
 import/extensions: 0
 react/jsx-filename-extension: 0`

That's reduced the number of errors by quite a lot. Got some left but it's not too bad and can work through them.

**Comment by grgur** [comment]
I'm ok with this for now. But we should come back to it to fine tune lint rules. 
I'm counting on @elodszopos, he's known to be the lint/test junky

**Comment by grgur** [comment]
A big thank you, James

**Comment by jamesallenuk** [comment]
Superb! Yeah would be good to settle on a nicely tuned set of rules for the project. I'll look at fixing the linting errors we have currently.

**Pull request merged**
